# Generated by Django 5.0.4 on 2024-05-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
