# Generated by Django 5.0.4 on 2024-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0011_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
    ]
